"""Shared pytest fixtures.

Fixture names tool builders' tests may rely on:
    app, client                      Flask app + test client
    sample_pdf_3p, sample_pdf_2p     Path -> samples/sample_3p.pdf / _2p.pdf
    sample_images                    list[Path] -> the 3 jpgs + 3 pngs
    sample_image_jpg, sample_image_png  first jpg / png of each
All paths are absolute pathlib.Path objects; samples are generated by
scripts/generate_samples.py.
"""
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app import create_app  # noqa: E402

SAMPLES = ROOT / "samples"


@pytest.fixture(scope="session")
def sample_pdf_3p() -> Path:
    p = SAMPLES / "sample_3p.pdf"
    assert p.is_file(), "run scripts/generate_samples.py first"
    return p


@pytest.fixture(scope="session")
def sample_pdf_2p() -> Path:
    p = SAMPLES / "sample_2p.pdf"
    assert p.is_file(), "run scripts/generate_samples.py first"
    return p


@pytest.fixture(scope="session")
def sample_images() -> list:
    imgs = sorted(SAMPLES.glob("sample_*.jpg")) + \
        sorted(SAMPLES.glob("sample_*.png"))
    assert imgs, "run scripts/generate_samples.py first"
    return imgs


@pytest.fixture(scope="session")
def sample_image_jpg() -> Path:
    return sorted(SAMPLES.glob("sample_*.jpg"))[0]


@pytest.fixture(scope="session")
def sample_image_png() -> Path:
    return sorted(SAMPLES.glob("sample_*.png"))[0]


@pytest.fixture()
def app(tmp_path):
    """App with job storage redirected into the per-test tmp dir and no
    scheduler (TestingConfig.SCHEDULER_ENABLED = False)."""
    app = create_app("testing")
    app.config.update(UPLOAD_ROOT=str(tmp_path / "uploads"),
                      OUTPUT_ROOT=str(tmp_path / "outputs"))
    (tmp_path / "uploads").mkdir(parents=True, exist_ok=True)
    (tmp_path / "outputs").mkdir(parents=True, exist_ok=True)
    yield app


@pytest.fixture()
def client(app):
    return app.test_client()
